package com.metroreader.app.domain.model

import com.metroreader.app.data.local.entity.BookEntity
import com.metroreader.app.data.local.entity.BookFormat

data class Book(
    val id: Long = 0,
    val title: String,
    val author: String = "",
    val filePath: String,
    val coverPath: String? = null,
    val format: BookFormat = BookFormat.UNKNOWN,
    val totalPages: Int = 0,
    val totalChapters: Int = 0,
    val fileSize: Long = 0L,
    val addedAt: Long = System.currentTimeMillis(),
    val lastOpenedAt: Long? = null,
    val estimatedReadingMinutes: Int = 0,
    val description: String = "",
    val publisher: String = "",
    val language: String = "",
    val isbn: String = "",
    val publishedDate: String = "",
    val accentColorHex: String = "#0078D4",
    val isFinished: Boolean = false,
    // Computed from ReadingProgressEntity
    val progressPercent: Float = 0f,
    val currentChapterIndex: Int = 0,
)

fun BookEntity.toDomain(progressPercent: Float = 0f, currentChapterIndex: Int = 0) = Book(
    id = id,
    title = title,
    author = author,
    filePath = filePath,
    coverPath = coverPath,
    format = format,
    totalPages = totalPages,
    totalChapters = totalChapters,
    fileSize = fileSize,
    addedAt = addedAt,
    lastOpenedAt = lastOpenedAt,
    estimatedReadingMinutes = estimatedReadingMinutes,
    description = description,
    publisher = publisher,
    language = language,
    isbn = isbn,
    publishedDate = publishedDate,
    accentColorHex = accentColorHex,
    isFinished = isFinished,
    progressPercent = progressPercent,
    currentChapterIndex = currentChapterIndex,
)

fun Book.toEntity() = BookEntity(
    id = id,
    title = title,
    author = author,
    filePath = filePath,
    coverPath = coverPath,
    format = format,
    totalPages = totalPages,
    totalChapters = totalChapters,
    fileSize = fileSize,
    addedAt = addedAt,
    lastOpenedAt = lastOpenedAt,
    estimatedReadingMinutes = estimatedReadingMinutes,
    description = description,
    publisher = publisher,
    language = language,
    isbn = isbn,
    publishedDate = publishedDate,
    accentColorHex = accentColorHex,
    isFinished = isFinished,
)
